name: Terraform Azure CI/CD

on:
  push:
    branches:
      - feature/rg_bhondu
      - feature/rg_rhondu
      - main


  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # ==========================================
  # FEATURE BRANCH / PULL REQUEST
  # INIT + VALIDATE + SCAN + PLAN
  # ==========================================
  terraform-plan:

    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Parent_Module

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          hide-progress: true
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Parent_Module/tfplan


  # ==========================================
  # MAIN BRANCH
  # INIT + PLAN + APPLY
  # ==========================================
  terraform-apply:

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: ./Parent_Module

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan